tasks:
  - name: Run Server
    before: |
      npm install opentest -g
    command: |
      cd server
      opentest server
  - name: Run Actor
    before: |
      npm install opentest -g
    command: |
      gp ports await 3000
      cd actor1
      opentest actor
  - name: Run Test
    command: |
      gp ports await 3000
      sleep 30
      DATA='{"actorTags":[],"environment":"","maxIterations":"1","sessionLabel":"'$(date)'","tests":[{"name":"list-all-public-crocodiles","path":"api"}]}' && \
      curl 'http://localhost:3000/api/session' \
      -H 'content-type: application/json;charset=UTF-8' \
      --data "$DATA"
vscode:
  extensions:
    - esbenp.prettier-vscode
