tasks:
  - name: Run Server
    before: |
      npm install opentest -g
    command: |
      cd server
      opentest server
  - name: Run Actor
    before: |
      npm install opentest -g
    command: |
      gp ports await 3000
      cd actor1
      opentest actor
  - name: Run Test
    command: |
      gp ports await 3000
      sleep 30
      source ./bin/run-test list-all-public-crocodiles
vscode:
  extensions:
    - esbenp.prettier-vscode
