tasks:
  - name: Run Server
    before: |
      npm install opentest -g
    command: |
      cd server
      opentest server
  - name: Run Actor
    before: |
      npm install opentest -g
    command: |
      gp ports await 3000
      cd actor1
      opentest actor
vscode:
  extensions:
    - anweber.vscode-httpyac